### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ardalis** [pmerson/ADR-template#3]
You may wish to add a license to this repo, so that others can feel free to "adapt and adopt" it (as I am). I suggest an MIT license.

**Comment by HowardvanRooijen** [comment]
+1 I'd love to include this template in [dotnet adr](https://github.com/endjin/dotnet-adr) but can only do that if you clarified the license. Thanks!

**Comment by pmerson** [comment]
Thank you @ardalis  and @HowardvanRooijen  for the suggestion and +1. 
I just added the MIT license. The intent of this repo was never to claim authorship, just to share what I use with the community. The MIT license seems to be the best fit. 😉
